#!/bin/bash

SEMS_VERSION="0.0.15.0"
SEMS_BASEFOLDER="$HOME/.sems"

mkdir -p $SEMS_BASEFOLDER/external

export SEMS_DATABASE=$HOME/.sems/db.json
export SEMS_DEBUG=False


pip3 uninstall sems
python setup.py  sdist
pip3 install dist/sems-$SEMS_VERSION.tar.gz
sems-start


